In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('establishmentsdata.csv')

In [4]:
df

,Unnamed: 0,ZIP_CODE,NAICS2017,NAICS2017_LABEL,EMPSZES_LABEL,ESTAB,RGCP_NAICS_FLAG,EDU_NAICS_FLAG
0,1,43001,236118,Residential remodelers,All establishments,4,N,N
1,2,43001,236118,Residential remodelers,Establishments with less than 5 employees,3,N,N
2,3,43001,524210,Insurance agencies and brokerages,All establishments,3,N,N
3,4,43001,722513,Limited-service restaurants,All establishments,3,N,N
4,5,43003,524126,Direct property and casualty insurance carriers,All establishments,3,N,N
...,...,...,...,...,...,...,...,...
43310,43311,45895,813110,Religious organizations,Establishments with 5 to 9 employees,3,Y,N
43311,43312,45895,813110,Religious organizations,Establishments with 10 to 19 employees,4,Y,N
43312,43313,45895,813410,Civic and social organizations,All establishments,4,Y,N
43313,43314,45895,813910,Business associations,All establishments,4,Y,N
43314,43315,45895,813910,Business associations,Establishments with less than 5 employees,3,Y,N

In [5]:
#health - physical & mental health 
#interested in exploring the ZIP codes and the services + resources that are offered there 
#communities that need the most help currently have less of the health services + resources

In [6]:
df1 = df[['ZIP_CODE', 'NAICS2017_LABEL']]
df1

       ZIP_CODE                                  NAICS2017_LABEL
0         43001                           Residential remodelers
1         43001                           Residential remodelers
2         43001                Insurance agencies and brokerages
3         43001                      Limited-service restaurants
4         43003  Direct property and casualty insurance carriers
...         ...                                              ...
43310     45895                          Religious organizations
43311     45895                          Religious organizations
43312     45895                   Civic and social organizations
43313     45895                            Business associations
43314     45895                            Business associations

[43315 rows x 2 columns]

In [7]:
df2 = df1.copy() 
df2 = df2.groupby(['ZIP_CODE']).count()
df2 = df2.sort_values('NAICS2017_LABEL', ascending = True)
df2 = df2.rename(columns = {'NAICS2017_LABEL': "Total Establishments"})
df2

          Total Establishments
ZIP_CODE
45218                        1
45623                        1
44629                        1
44628                        1
45657                        1
...                        ...
44122                      340
45069                      355
45202                      360
44060                      365
43215                      417

[828 rows x 1 columns]

In [8]:
#medical services (physical health) 
df3 = df1.copy() 
filter1 = df3['NAICS2017_LABEL'] == 'Offices of physicians (except mental health specialists)'
filter2 = df3['NAICS2017_LABEL'] == 'Offices of dentists'
filter3 = df3['NAICS2017_LABEL'] == 'Offices of chiropractors'
filter4 = df3['NAICS2017_LABEL'] == 'Offices of physical, occupational and speech therapists, and audiologists'
df3 = df3.where(filter1 | filter2 | filter3 | filter4)
df3 = df3.dropna()
df3 = df3.groupby(['ZIP_CODE']).count()
df3 = df3.sort_values('NAICS2017_LABEL', ascending = True)
df3 = df3.rename(columns = {'NAICS2017_LABEL': 'Medical Service Establishments'})
df3

          Medical Service Establishments
ZIP_CODE
43793.0                                1
44040.0                                1
44137.0                                1
43515.0                                1
44273.0                                1
...                                  ...
45242.0                               16
43213.0                               16
43230.0                               16
43026.0                               17
45069.0                               18

[392 rows x 1 columns]

In [9]:
#recreation & entertainment (mental health)

df4 = df1.copy() 
filter1 = df4['NAICS2017_LABEL'] == 'Fitness and recreational sports centers'
filter2 = df4['NAICS2017_LABEL'] == 'Sports and recreation instruction'
filter3 = df4['NAICS2017_LABEL'] == 'Fine arts schools'
filter4 = df4['NAICS2017_LABEL'] == 'Beauty salons'
filter5 = df4['NAICS2017_LABEL'] == 'Nail salons'
filter6 = df4['NAICS2017_LABEL'] == 'Drinking places (alcoholic beverages)'
filter7 = df4['NAICS2017_LABEL'] == 'Full-service restaurants'
filter8 = df4['NAICS2017_LABEL'] == 'Limited-service restaurants'
filter9 = df4['NAICS2017_LABEL'] == 'Other personal care services'
df4 = df4.where(filter1 | filter2 | filter3 | filter4 | filter5 | filter6 | filter7 | filter8 | filter9)
df4 = df4.dropna()
df4 = df4.groupby(['ZIP_CODE']).count()
df4 = df4.sort_values('NAICS2017_LABEL', ascending = True)
df4 = df4.rename(columns = {'NAICS2017_LABEL': 'Recreation & Entertainment Establishments'})
df4

          Recreation & Entertainment Establishments
ZIP_CODE
43001.0                                           1
43845.0                                           1
43832.0                                           1
43762.0                                           1
45252.0                                           1
...                                             ...
45242.0                                          27
45069.0                                          29
43230.0                                          29
45459.0                                          29
43065.0                                          30

[577 rows x 1 columns]

In [11]:
#additional consideration 
#child-care access (more access to child care means more time for parents)

df5 = df1.copy() 
filter1 = df5['NAICS2017_LABEL'] == 'Child day care services'
df5 = df5.where(filter1)
df5 = df5.dropna()
df5 = df5.groupby(['ZIP_CODE']).count()
df5 = df5.sort_values('NAICS2017_LABEL', ascending = True)
df5 = df5.rename(columns = {'NAICS2017_LABEL': 'Child Care Services'})
df5

          Child Care Services
ZIP_CODE
44202.0                     1
44903.0                     1
44906.0                     1
44092.0                     1
45005.0                     1
...                       ...
43224.0                     5
43231.0                     5
43026.0                     5
43017.0                     5
43229.0                     5

[300 rows x 1 columns]