In [24]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
plt.style.use('ggplot')

In [25]:
rentdata = pd.read_csv('shared_data_read_only/HUD_Rent_Data.csv')
columns = rentdata.columns
dtypes = rentdata.dtypes

In [26]:
ohio_rent = rentdata[rentdata['HUD Metro Fair Market Rent Area Name'].str.contains('OH MSA')]
ohio_rent.to_excel("ohio_rent_data.xlsx")

calc_stats = ohio_rent.copy()
calc_stats = calc_stats.drop(columns = ['ZIP\nCode', 'HUD Area Code', 'SAFMR\n0BR'])

calc_stats.rename(columns={"HUD Metro Fair Market Rent Area Name": "name", "SAFMR\n1BR": "1br", "SAFMR\n2BR": "2br", "SAFMR\n3BR": "3br", "SAFMR\n4BR": "4br"})
calc_stats.to_excel("stats_data.xlsx")

In [34]:
newdata = pd.read_excel('Team-13/new_data.xlsx')
newdata.groupby(['HUD Metro Fair Market Rent Area Name']).mean()

,Unnamed: 0,SAFMR\n1BR,SAFMR\n2BR,SAFMR\n3BR,SAFMR\n4BR
HUD Metro Fair Market Rent Area Name,,,,,
"Akron, OH MSA",89.0,844.647887,1072.253521,1347.323944,1438.591549
"Canton-Massillon, OH MSA",3581.5,703.529412,918.529412,1154.264706,1229.705882
"Cleveland-Elyria, OH MSA",5443.5,952.222222,1158.333333,1497.063492,1595.952381
"Dayton-Kettering, OH MSA",6758.0,813.370787,1040.786517,1353.483146,1484.157303
"Lima, OH MSA",12782.0,744.347826,955.652174,1189.565217,1342.608696
"Mansfield, OH MSA",14254.5,749.000000,932.000000,1242.000000,1412.000000
"Springfield, OH MSA",24124.5,761.666667,984.583333,1214.166667,1336.666667
"Weirton-Steubenville, WV-OH MSA",26578.0,702.820513,890.769231,1207.948718,1313.076923
"Wheeling, WV-OH MSA",26735.0,739.795918,926.122449,1210.612245,1376.122449

In [60]:
data_by_zip = ohio_rent.copy()
data_by_zip = data_by_zip.drop(columns = ['HUD Area Code', 'HUD Metro Fair Market Rent Area Name', 'SAFMR\n0BR'])
cols = ['SAFMR\n1BR', 'SAFMR\n2BR', 'SAFMR\n3BR', 'SAFMR\n4BR']

# data_by_zip['SAFMR\n1BR'] = data_by_zip['SAFMR\n1BR'].str.replace('$', '')
# data_by_zip['SAFMR\n2BR'] = data_by_zip['SAFMR\n2BR'].str.replace('$', '')
# data_by_zip['SAFMR\n3BR'] = data_by_zip['SAFMR\n3BR'].str.replace('$', '')
# data_by_zip['SAFMR\n4BR'] = data_by_zip['SAFMR\n4BR'].str.replace('$', '')

for col in cols:
    data_by_zip[col] = data_by_zip[col].str.replace('$', '')
    data_by_zip[col] = data_by_zip[col].str.replace(',', '')
    data_by_zip[col] = data_by_zip[col].astype(int)
    
affordable_proportion = (data_by_zip['SAFMR\n4BR'] < 1400).groupby(data_by_zip['ZIP\nCode']).mean()

data_by_zip.to_excel("Team-13/rentbyzipcode.xlsx")

/opt/tljh/user/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  # This is added back by InteractiveShellApp.init_path()

In [61]:

affordable_proportion = (data_by_zip['SAFMR\n4BR'] < 1400).groupby(data_by_zip['ZIP\nCode']).mean()
afford.to_excel("Team-13/rentbyzipcode.xlsx")

In [62]:
affordable_proportion

ZIP\nCode
26003    False
26030     True
26031     True
26032     True
26033    False
         ...
45877    False
45887     True
45894     True
45895     True
45896    False
Name: SAFMR\n4BR, Length: 470, dtype: bool

In [75]:
zip_dict = {}
for index, row in data_by_zip.iterrows():
    if row['ZIP\nCode'] not in zip_dict:
        zip_dict[row['ZIP\nCode']] = [0, 0] # first is below 1400, second is total
    if row['SAFMR\n3BR'] <= 1400:
        zip_dict[row['ZIP\nCode']][0] += 1
    zip_dict[row['ZIP\nCode']][1] += 1

In [76]:
data_by_zip.columns

Index(['ZIP\nCode', 'SAFMR\n1BR', 'SAFMR\n2BR', 'SAFMR\n3BR', 'SAFMR\n4BR'], dtype='object')

In [80]:
data_with_affordable = pd.DataFrame(zip_dict).transpose()
data_with_affordable['Proportion'] = data_with_affordable[0] / data_with_affordable[1]
data_with_affordable

       0  1  Proportion
44056  0  1         0.0
44067  0  1         0.0
44087  0  1         0.0
44141  0  2         0.0
44201  2  2         1.0
...   .. ..         ...
43972  1  1         1.0
43973  1  1         1.0
43977  1  1         1.0
43983  1  1         1.0
43985  1  1         1.0

[470 rows x 3 columns]

In [81]:
data_with_affordable.to_excel("Team-13/rent_data_feature_proportions.xlsx")