In [1]:
import pandas as pd

In [2]:
pi_rankings = pd.read_excel("../shared_data_read_only/District_and_School_Performance_Index_Ranking.xlsx", sheet_name=2)
value_add_rankings = pd.read_excel("../shared_data_read_only/District_Value_Added_Ranking.xlsx", sheet_name = 1)

In [3]:
rankings = pi_rankings
duplicateRowsName = rankings[rankings.duplicated(['LEA Name'])]
duplicateRowsIRN = rankings[rankings.duplicated(['LEA IRN'])]
duplicateRowsBoth = rankings[rankings.duplicated(['LEA IRN', 'LEA Name'])]

In [4]:
len(rankings)

3295

In [5]:
combined_rankings = rankings.merge(value_add_rankings, left_on = 'LEA IRN', right_on='District IRN', how = 'inner') # Merged with Value Added File, inner because we ignored 15 entries that had NaN
combined_rankings = combined_rankings[combined_rankings['2023 PI for Ranking'] != 'NC'] # Ignore the NC since they are not calculated
combined_rankings['2023 PI for Rankings'] = combined_rankings["2023 PI for Ranking"].astype(float) 
# Removing ones that are not in both which was 15+17 and also NC which is not calculated and in respect to montessories and such

In [6]:
combined_rankings[['LEA IRN', 'District IRN', 'District Name', 'LEA Name']]

,LEA IRN,District IRN,District Name,LEA Name
0,44826,44826,Steubenville City,Steubenville City
1,44826,44826,Steubenville City,Steubenville City
2,44826,44826,Steubenville City,Steubenville City
3,44826,44826,Steubenville City,Steubenville City
4,44826,44826,Steubenville City,Steubenville City
...,...,...,...,...
3275,133504,133504,ReGeneration Schools Avondale Elementary,ReGeneration Schools Avondale Elementary
3276,134122,134122,Autism Model School,Autism Model School
3277,938,938,East Bridge Academy of Excellence,East Bridge Academy of Excellence
3278,17212,17212,Dampe Community School,Dampe Community School
3279,576,576,Elevated Excellence Academy,Elevated Excellence Academy

In [7]:
combined_rankings

,2023 PI Ranking,LEA Name,Building Name,2023 PI for Ranking,2023 PI Proxy Descriptor,2023 Achievement Rating,ODE Designated County_x,LEA IRN,Building IRN,Building Org Type,...,ODE Designated County_y,District Org Type,District Org Status,2023 Grade Span_y,2023 Value-Added Star Rating,2023 Value-Added Gain Index,2023 Value-Added Effect Size,2023 Value-Added Index Ranking,2023 Value-Added Effect Size Ranking,2023 PI for Rankings
0,1,Steubenville City,Wells Academy,117.181,REAL PI,5 Stars,Jefferson,44826,40246,Public School,...,Jefferson,Public District,Open,K-12,4 Stars,3.73,0.05,182,229,117.181
1,11,Steubenville City,McKinley STEM Academy,112.5,REAL PI,5 Stars,Jefferson,44826,17520,Public School,...,Jefferson,Public District,Open,K-12,4 Stars,3.73,0.05,182,229,112.500
2,27,Steubenville City,Pugliese Elementary West,110.839,REAL PI,5 Stars,Jefferson,44826,4200,Public School,...,Jefferson,Public District,Open,K-12,4 Stars,3.73,0.05,182,229,110.839
3,236,Steubenville City,Harding Middle School,103.558,REAL PI,5 Stars,Jefferson,44826,15180,Public School,...,Jefferson,Public District,Open,K-12,4 Stars,3.73,0.05,182,229,103.558
4,281,Steubenville City,East Garfield Elementary School,102.773,REAL PI,5 Stars,Jefferson,44826,32433,Public School,...,Jefferson,Public District,Open,K-12,4 Stars,3.73,0.05,182,229,102.773
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275,3262,ReGeneration Schools Avondale Elementary,ReGeneration Schools Avondale Elementary,37.839,REAL PI,1 Star,Hamilton,133504,133504,Community School,...,Hamilton,Community School,Open,K-4,2 Stars,-2.37,-0.11,581,708,37.839
3276,3270,Autism Model School,Autism Model School,36.623,REAL PI,1 Star,Lucas,134122,134122,Community School,...,Lucas,Community School,Open,"K,1-12,UNG",3 Stars,0.52,0.10,367,130,36.623
3277,3276,East Bridge Academy of Excellence,East Bridge Academy of Excellence,35.192,REAL PI,1 Star,Franklin,938,938,Community School,...,Franklin,Community School,Open,K-8,3 Stars,-0.01,0.00,415,398,35.192
3278,3280,Dampe Community School,Dampe Community School,33.257,REAL PI,1 Star,Hamilton,17212,17212,Community School,...,Hamilton,Community School,Open,K-8,4 Stars,2.71,0.14,230,83,33.257
3279,3281,Elevated Excellence Academy,Elevated Excellence Academy,31.969,REAL PI,1 Star,Hamilton,576,576,Community School,...,Hamilton,Community School,Open,K-8,3 Stars,-1.47,-0.12,522,735,31.969

In [8]:
grouped_county = combined_rankings.groupby('ODE Designated County_x') # Group by county
grouped_dict_variance_county = grouped_county['2023 PI for Rankings'].var().to_dict() # Dictionary with county and variance
grouped_dict_counts_county = grouped_county.size().to_dict() # Counties with 3 of schools in it

In [9]:
grouped_dict_variance_county

{'Adams': 48.77684555357137,
 'Allen': 279.4335873295456,
 'Ashland': 60.369828970588244,
 'Ashtabula': 84.60027967956995,
 'Athens': 112.91279974264714,
 'Auglaize': 93.91102149264704,
 'Belmont': 101.38949749134201,
 'Brown': 61.74128089583329,
 'Butler': 199.92364992532416,
 'Carroll': 20.806006333333404,
 'Champaign': 71.1929325523809,
 'Clark': 270.48536255195694,
 'Clermont': 70.56192206039486,
 'Clinton': 48.60629042307697,
 'Columbiana': 119.96583140106945,
 'Coshocton': 45.44210854444442,
 'Crawford': 81.16543559064333,
 'Cuyahoga': 473.46506210456147,
 'Darke': 78.56448693684213,
 'Defiance': 75.1848590549451,
 'Delaware': 63.19637154901956,
 'Erie': 150.36476840909106,
 'Fairfield': 71.94496966384781,
 'Fayette': 47.781834476190475,
 'Franklin': 393.56123661430223,
 'Fulton': 48.07799368421053,
 'Gallia': 112.55462553846154,
 'Geauga': 117.02916601052637,
 'Greene': 150.1996747670456,
 'Guernsey': 108.19782042307685,
 'Hamilton': 490.7267543559002,
 'Hancock': 106.66092599596784,
 'Hardin': 42.7473295454546,
 'Harrison': 29.757781333333313,
 'Henry': 25.888743566666644,
 'Highland': 40.90439155882362,
 'Hocking': 94.82292966666667,
 'Holmes': 133.69581905000004,
 'Huron': 65.30399256277067,
 'Jackson': 74.56090629090906,
 'Jefferson': 180.04387317099585,
 'Knox': 68.54918104575154,
 'Lake': 242.06856624547518,
 'Lawrence': 107.00935578656119,
 'Licking': 125.05493011152898,
 'Logan': 29.21746153787874,
 'Lorain': 378.99716254202565,
 'Lucas': 403.4464179410793,
 'Madison': 54.75112606666681,
 'Mahoning': 484.0795306368155,
 'Marion': 190.83856730952385,
 'Medina': 160.39762671097571,
 'Meigs': 45.60656678571426,
 'Mercer': 81.96695204093572,
 'Miami': 71.78253933522726,
 'Monroe': 28.39839723809523,
 'Montgomery': 428.2429084541651,
 'Morgan': 10.249355299999948,
 'Morrow': 40.9016835636364,
 'Muskingum': 204.90605750793654,
 'Noble': 33.84350958333338,
 'Ottawa': 28.119288683823548,
 'Paulding': 65.75303515555552,
 'Perry': 90.01233964835168,
 'Pickaway': 163.78188044999987,
 'Pike': 25.334694974359056,
 'Portage': 93.91749864059196,
 'Preble': 44.145122250000036,
 'Putnam': 49.9209306839827,
 'Richland': 180.36214362348173,
 'Ross': 50.570345992094865,
 'Sandusky': 56.6509168676469,
 'Scioto': 110.37102637816113,
 'Seneca': 272.1150432810459,
 'Shelby': 217.67541823333346,
 'Stark': 326.6495380305924,
 'Summit': 375.8227558253181,
 'Trumbull': 151.43100964586145,
 'Tuscarawas': 72.36857642342346,
 'Union': 43.84703638235286,
 'Van Wert': 65.24990096363642,
 'Vinton': 117.45739280000005,
 'Warren': 52.47639712550594,
 'Washington': 74.36289594473674,
 'Wayne': 80.39398346514933,
 'Williams': 26.58156320879123,
 'Wood': 125.74125492941175,
 'Wyandot': 33.86511949999998}

In [10]:
# Add variance column with variance by zip code for each city
combined_rankings['Variance'] = None
for index, row in combined_rankings.iterrows():
    currCounty = row['ODE Designated County_x']
    if grouped_dict_counts_county[currCounty] >= 20:
        combined_rankings.at[index, 'Variance'] = grouped_dict_variance_county[currCounty]
    else:
        combined_rankings.at[index, 'Variance'] = 1000

In [11]:
len(combined_rankings[combined_rankings['Variance'] == 1000])

527

In [12]:
combined_rankings.columns

Index(['2023 PI Ranking', 'LEA Name', 'Building Name', '2023 PI for Ranking',
       '2023 PI Proxy Descriptor', '2023 Achievement Rating',
       'ODE Designated County_x', 'LEA IRN', 'Building IRN',
       'Building Org Type', 'Building Type',
       'Building Org Status as of 9/14/23', '2023 Grade Span_x',
       'Additional Comments', 'District IRN', 'District Name',
       'ODE Designated County_y', 'District Org Type', 'District Org Status',
       '2023 Grade Span_y', '2023 Value-Added Star Rating',
       '2023 Value-Added Gain Index', '2023 Value-Added Effect Size',
       '2023 Value-Added Index Ranking',
       '2023 Value-Added Effect Size Ranking', '2023 PI for Rankings',
       'Variance'],
      dtype='object')

TypeError: to_excel() missing 1 required positional argument: 'excel_writer'